/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    locations: Location;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The browser tab title, and the page's name here.
   */
  title: string;
  /**
   * The page's address: /foundation for “foundation”. Lowercase letters, numbers and hyphens.
   */
  slug: string;
  layout: (
    | {
        /**
         * Optional: a short line above the title.
         */
        eyebrow?: string | null;
        title: string;
        subtitle?: string | null;
        image: number | Media;
        /**
         * Which edge of the photo stays in view when it's cropped (centred if empty).
         */
        imagePosition?: ('top' | 'bottom' | 'left' | 'right') | null;
        /**
         * Optional: links to a page. Leave both empty for no button.
         */
        cta?: {
          label?: string | null;
          /**
           * A page (/co-living), a full URL or mailto:…
           */
          href?: string | null;
        };
        /**
         * Optional: opens this video over the page. Used instead of the button above.
         */
        video?: {
          label?: string | null;
          /**
           * YouTube, Vimeo or an .mp4
           */
          url?: string | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        heading: string;
        /**
         * Leave a blank line between paragraphs.
         */
        body: string;
        layout?: ('split' | 'stacked') | null;
        buttons?: ('light' | 'dark' | 'contact') | null;
        /**
         * Optional: leave both empty for no button.
         */
        cta?: {
          label?: string | null;
          /**
           * A page (/co-living), a full URL or mailto:…
           */
          href?: string | null;
        };
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'intro';
      }
    | {
        heading: string;
        intro?: string | null;
        items?:
          | {
              /**
               * Optional: shown beside the item.
               */
              icon?:
                | (
                    | 'Api'
                    | 'Automate'
                    | 'BarKitchen'
                    | 'Basin'
                    | 'Bed'
                    | 'Bike'
                    | 'Bill'
                    | 'Bus'
                    | 'Calendar'
                    | 'CalendarCheck'
                    | 'Car'
                    | 'Cctv'
                    | 'Check'
                    | 'Chef'
                    | 'Cocktail'
                    | 'Community'
                    | 'Crowd'
                    | 'Database'
                    | 'DealFlow'
                    | 'Desk'
                    | 'Dining'
                    | 'DoorEntry'
                    | 'Dumbbell'
                    | 'FeasibilityModel'
                    | 'FruitBowl'
                    | 'Groceries'
                    | 'Guard'
                    | 'Hack'
                    | 'HandsHeart'
                    | 'Handshake'
                    | 'Help'
                    | 'Hob'
                    | 'Icon360'
                    | 'Info'
                    | 'IntegrateData'
                    | 'Integrations'
                    | 'Lion'
                    | 'LocationPin'
                    | 'Lock'
                    | 'Lounge'
                    | 'Mail'
                    | 'ManageMembership'
                    | 'MeetingTable'
                    | 'MemberSupport'
                    | 'Membership'
                    | 'Microwave'
                    | 'Outdoor'
                    | 'Oven'
                    | 'Padlock'
                    | 'People'
                    | 'Plane'
                    | 'Play'
                    | 'PrivateOffice'
                    | 'QuoteMark'
                    | 'Relationships'
                    | 'Reporting'
                    | 'Restaurant'
                    | 'RestaurantsNearby'
                    | 'RoomAllocation'
                    | 'RoomPricing'
                    | 'Roundel'
                    | 'Router'
                    | 'Scales'
                    | 'Shelves'
                    | 'SmartHome'
                    | 'SocialNetwork'
                    | 'Sofa'
                    | 'SprayBottle'
                    | 'Sprout'
                    | 'Star'
                    | 'SunCloud'
                    | 'TapeMeasure'
                    | 'TeamChat'
                    | 'TrackMarket'
                    | 'Train'
                    | 'WashingMachine'
                    | 'Workshop'
                    | 'Wrench'
                  )
                | null;
              title: string;
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'checklist';
      }
    | {
        heading?: string | null;
        intro?: string | null;
        cards?:
          | {
              title: string;
              text: string;
              image: number | Media;
              /**
               * Which edge of the photo stays in view when it's cropped (centred if empty).
               */
              position?: ('top' | 'bottom' | 'left' | 'right') | null;
              ctaLabel: string;
              ctaHref: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional, e.g. “Read more press articles”.
         */
        moreLink?: {
          label?: string | null;
          href?: string | null;
        };
        cardStyle?: ('dark' | 'light') | null;
        imageShape?: ('wide' | 'tall') | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'linkCards';
      }
    | {
        heading: string;
        /**
         * Leave a blank line between paragraphs.
         */
        body: string;
        images: {
          main: number | Media;
          top: number | Media;
          bottom: number | Media;
        };
        side?: ('left' | 'right') | null;
        /**
         * Optional: leave both empty for no button.
         */
        cta?: {
          label?: string | null;
          /**
           * A page (/co-living), a full URL or mailto:…
           */
          href?: string | null;
        };
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'collageSplit';
      }
    | {
        heading: string;
        intro?: string | null;
        people?:
          | {
              name: string;
              photo: number | Media;
              /**
               * Optional: their video, as a YouTube or Vimeo link or an .mp4.
               */
              video?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        heading: string;
        intro?: string | null;
        quotes?:
          | {
              quote: string;
              publication: string;
              /**
               * Optional: the publication's logo, ideally an SVG. Without one, its name is shown.
               */
              logo?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pressQuotes';
      }
    | {
        heading: string;
        intro?: string | null;
        people?:
          | {
              name: string;
              role: string;
              photo: number | Media;
              /**
               * Which edge of the photo stays in view when it's cropped (centred if empty).
               */
              position?: ('top' | 'bottom' | 'left' | 'right') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamGrid';
      }
    | {
        heading: string;
        intro?: string | null;
        items?:
          | {
              question: string;
              /**
               * Leave a blank line between paragraphs.
               */
              answer: string;
              numbered?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        topics?:
          | {
              topic: string;
              items?:
                | {
                    question: string;
                    /**
                     * Leave a blank line between paragraphs.
                     */
                    answer: string;
                    numbered?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqDirectory';
      }
    | {
        /**
         * Lists the job pages (written in code, in content/careers.ts). Link here with #open-positions.
         */
        heading: string;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openPositions';
      }
    | {
        /**
         * The logos and photos to download are in code (content/press.ts).
         */
        heading: string;
        intro?: string | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaKit';
      }
    | {
        cards?:
          | {
              heading: string;
              image: number | Media;
              /**
               * Which edge of the photo stays in view when it's cropped (centred if empty).
               */
              position?: ('top' | 'bottom' | 'left' | 'right') | null;
              ctaLabel: string;
              ctaHref: string;
              /**
               * Optional: an enquiry form instead of the link (which then isn't used).
               */
              enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'promoCards';
      }
    | {
        heading: string;
        intro?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'socialLinks';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for people who can't see it.
   */
  alt: string;
  blur?: string | null;
  source?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Working spaces, serviced living houses and event venues: their cards and their own pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * The page's address after its type's, e.g. /working/bedford-square for “bedford-square”.
   */
  slug: string;
  type: 'working' | 'serviced' | 'venue';
  /**
   * Neighbourhood, e.g. Bloomsbury
   */
  area: string;
  postcode: string;
  /**
   * e.g. “From £150 per month”, or a venue's capacity.
   */
  fromPrice: string;
  image: number | Media;
  /**
   * Transport and key facilities: the card's tiles and the page header's rows (up to 4).
   */
  features?:
    | {
        label: string;
        icon:
          | 'Api'
          | 'Automate'
          | 'BarKitchen'
          | 'Basin'
          | 'Bed'
          | 'Bike'
          | 'Bill'
          | 'Bus'
          | 'Calendar'
          | 'CalendarCheck'
          | 'Car'
          | 'Cctv'
          | 'Check'
          | 'Chef'
          | 'Cocktail'
          | 'Community'
          | 'Crowd'
          | 'Database'
          | 'DealFlow'
          | 'Desk'
          | 'Dining'
          | 'DoorEntry'
          | 'Dumbbell'
          | 'FeasibilityModel'
          | 'FruitBowl'
          | 'Groceries'
          | 'Guard'
          | 'Hack'
          | 'HandsHeart'
          | 'Handshake'
          | 'Help'
          | 'Hob'
          | 'Icon360'
          | 'Info'
          | 'IntegrateData'
          | 'Integrations'
          | 'Lion'
          | 'LocationPin'
          | 'Lock'
          | 'Lounge'
          | 'Mail'
          | 'ManageMembership'
          | 'MeetingTable'
          | 'MemberSupport'
          | 'Membership'
          | 'Microwave'
          | 'Outdoor'
          | 'Oven'
          | 'Padlock'
          | 'People'
          | 'Plane'
          | 'Play'
          | 'PrivateOffice'
          | 'QuoteMark'
          | 'Relationships'
          | 'Reporting'
          | 'Restaurant'
          | 'RestaurantsNearby'
          | 'RoomAllocation'
          | 'RoomPricing'
          | 'Roundel'
          | 'Router'
          | 'Scales'
          | 'Shelves'
          | 'SmartHome'
          | 'SocialNetwork'
          | 'Sofa'
          | 'SprayBottle'
          | 'Sprout'
          | 'Star'
          | 'SunCloud'
          | 'TapeMeasure'
          | 'TeamChat'
          | 'TrackMarket'
          | 'Train'
          | 'WashingMachine'
          | 'Workshop'
          | 'Wrench';
        id?: string | null;
      }[]
    | null;
  /**
   * Leave a blank line between paragraphs.
   */
  intro: string;
  gallery?:
    | {
        image: number | Media;
        /**
         * Shown with the photo, e.g. “Lounge area”. Leave empty to use the photo's alt text.
         */
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Pricing cards. Leave empty to leave pricing out (e.g. venues, priced on request).
   */
  prices?:
    | {
        label: string;
        amount: string;
        period: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Facilities, in groups (a label is optional). Working spaces can leave it empty to show the standard list every working space has.
   */
  included?:
    | {
        label?: string | null;
        items?:
          | {
              label: string;
              icon:
                | 'Api'
                | 'Automate'
                | 'BarKitchen'
                | 'Basin'
                | 'Bed'
                | 'Bike'
                | 'Bill'
                | 'Bus'
                | 'Calendar'
                | 'CalendarCheck'
                | 'Car'
                | 'Cctv'
                | 'Check'
                | 'Chef'
                | 'Cocktail'
                | 'Community'
                | 'Crowd'
                | 'Database'
                | 'DealFlow'
                | 'Desk'
                | 'Dining'
                | 'DoorEntry'
                | 'Dumbbell'
                | 'FeasibilityModel'
                | 'FruitBowl'
                | 'Groceries'
                | 'Guard'
                | 'Hack'
                | 'HandsHeart'
                | 'Handshake'
                | 'Help'
                | 'Hob'
                | 'Icon360'
                | 'Info'
                | 'IntegrateData'
                | 'Integrations'
                | 'Lion'
                | 'LocationPin'
                | 'Lock'
                | 'Lounge'
                | 'Mail'
                | 'ManageMembership'
                | 'MeetingTable'
                | 'MemberSupport'
                | 'Membership'
                | 'Microwave'
                | 'Outdoor'
                | 'Oven'
                | 'Padlock'
                | 'People'
                | 'Plane'
                | 'Play'
                | 'PrivateOffice'
                | 'QuoteMark'
                | 'Relationships'
                | 'Reporting'
                | 'Restaurant'
                | 'RestaurantsNearby'
                | 'RoomAllocation'
                | 'RoomPricing'
                | 'Roundel'
                | 'Router'
                | 'Scales'
                | 'Shelves'
                | 'SmartHome'
                | 'SocialNetwork'
                | 'Sofa'
                | 'SprayBottle'
                | 'Sprout'
                | 'Star'
                | 'SunCloud'
                | 'TapeMeasure'
                | 'TeamChat'
                | 'TrackMarket'
                | 'Train'
                | 'WashingMachine'
                | 'Workshop'
                | 'Wrench';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Street address: drives the map and the “open in Maps” links. Without one, the map is left out.
   */
  address?: string | null;
  directionsIntro: string;
  travelModes?:
    | {
        label: string;
        icon: 'underground' | 'overground' | 'bus' | 'car';
        /**
         * One step per line.
         */
        steps: string;
        mapsUrl: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              image?: T;
              imagePosition?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              video?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              id?: T;
              blockName?: T;
            };
        intro?:
          | T
          | {
              heading?: T;
              body?: T;
              layout?: T;
              buttons?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        linkCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    image?: T;
                    position?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                  };
              moreLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              cardStyle?: T;
              imageShape?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        collageSplit?:
          | T
          | {
              heading?: T;
              body?: T;
              images?:
                | T
                | {
                    main?: T;
                    top?: T;
                    bottom?: T;
                  };
              side?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              intro?: T;
              people?:
                | T
                | {
                    name?: T;
                    photo?: T;
                    video?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        pressQuotes?:
          | T
          | {
              heading?: T;
              intro?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    publication?: T;
                    logo?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              people?:
                | T
                | {
                    name?: T;
                    role?: T;
                    photo?: T;
                    position?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    numbered?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faqDirectory?:
          | T
          | {
              topics?:
                | T
                | {
                    topic?: T;
                    items?:
                      | T
                      | {
                          question?: T;
                          answer?: T;
                          numbered?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        openPositions?:
          | T
          | {
              heading?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        mediaKit?:
          | T
          | {
              heading?: T;
              intro?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        promoCards?:
          | T
          | {
              cards?:
                | T
                | {
                    heading?: T;
                    image?: T;
                    position?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    enquiry?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        socialLinks?:
          | T
          | {
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  type?: T;
  area?: T;
  postcode?: T;
  fromPrice?: T;
  image?: T;
  features?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  intro?: T;
  gallery?:
    | T
    | {
        image?: T;
        name?: T;
        id?: T;
      };
  prices?:
    | T
    | {
        label?: T;
        amount?: T;
        period?: T;
        id?: T;
      };
  included?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  address?: T;
  directionsIntro?: T;
  travelModes?:
    | T
    | {
        label?: T;
        icon?: T;
        steps?: T;
        mapsUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blur?: T;
  source?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}