/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    locations: Location;
    rooms: Room;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    contactDetails: ContactDetail;
    socialLinks: SocialLink;
    locationPages: LocationPage;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    contactDetails: ContactDetailsSelect<false> | ContactDetailsSelect<true>;
    socialLinks: SocialLinksSelect<false> | SocialLinksSelect<true>;
    locationPages: LocationPagesSelect<false> | LocationPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The browser tab title, and the page's name here.
   */
  title: string;
  /**
   * The page's address: /foundation for “foundation”. Lowercase letters, numbers and hyphens.
   */
  slug: string;
  /**
   * Optional: an enquiry button that stays on screen on mobile, opening this form.
   */
  floatingEnquiry?: ('living' | 'working' | 'serviced' | 'events') | null;
  layout: (
    | {
        /**
         * Optional: a short line above the title.
         */
        eyebrow?: string | null;
        title: string;
        subtitle?: string | null;
        image: number | Media;
        /**
         * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
         */
        imagePosition?: ('top' | 'bottom' | 'left' | 'right') | null;
        button?: {
          /**
           * A video button has a play icon and opens the video over the page.
           */
          type?: ('none' | 'button' | 'video') | null;
          opens?: ('link' | 'enquiry') | null;
          /**
           * A page, another site, mailto:… or #section
           */
          href?: string | null;
          enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
          /**
           * YouTube, Vimeo or an .mp4
           */
          videoUrl?: string | null;
          /**
           * For an enquiry form, leave empty to use the form's usual label (e.g. “Book a viewing”).
           */
          label?: string | null;
          arrow?: boolean | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        heading: string;
        /**
         * Leave a blank line between paragraphs.
         */
        body: string;
        layout?: ('split' | 'stacked') | null;
        buttons?: ('light' | 'dark' | 'contact' | 'enquiry') | null;
        /**
         * Optional: leave both empty for no button.
         */
        cta?: {
          label?: string | null;
          /**
           * A page, another site, mailto:… or #section
           */
          href?: string | null;
        };
        enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'intro';
      }
    | {
        heading: string;
        intro?: string | null;
        items?:
          | {
              /**
               * Optional: shown beside the item.
               */
              icon?:
                | (
                    | 'Api'
                    | 'Automate'
                    | 'BarKitchen'
                    | 'Basin'
                    | 'Bed'
                    | 'Bike'
                    | 'Bill'
                    | 'Bus'
                    | 'Calendar'
                    | 'CalendarCheck'
                    | 'Car'
                    | 'Cctv'
                    | 'Check'
                    | 'Chef'
                    | 'Cocktail'
                    | 'Community'
                    | 'Crowd'
                    | 'Database'
                    | 'DealFlow'
                    | 'Desk'
                    | 'Dining'
                    | 'DoorEntry'
                    | 'Dumbbell'
                    | 'FeasibilityModel'
                    | 'FruitBowl'
                    | 'Groceries'
                    | 'Guard'
                    | 'Hack'
                    | 'HandsHeart'
                    | 'Handshake'
                    | 'Help'
                    | 'Hob'
                    | 'Icon360'
                    | 'Info'
                    | 'IntegrateData'
                    | 'Integrations'
                    | 'Lion'
                    | 'LocationPin'
                    | 'Lock'
                    | 'Lounge'
                    | 'Mail'
                    | 'ManageMembership'
                    | 'MeetingTable'
                    | 'MemberSupport'
                    | 'Membership'
                    | 'Microwave'
                    | 'Outdoor'
                    | 'Oven'
                    | 'Padlock'
                    | 'People'
                    | 'Plane'
                    | 'Play'
                    | 'PrivateOffice'
                    | 'QuoteMark'
                    | 'Relationships'
                    | 'Reporting'
                    | 'Restaurant'
                    | 'RestaurantsNearby'
                    | 'RoomAllocation'
                    | 'RoomPricing'
                    | 'Roundel'
                    | 'Router'
                    | 'Scales'
                    | 'Shelves'
                    | 'SmartHome'
                    | 'SocialNetwork'
                    | 'Sofa'
                    | 'SprayBottle'
                    | 'Sprout'
                    | 'Star'
                    | 'SunCloud'
                    | 'TapeMeasure'
                    | 'TeamChat'
                    | 'TrackMarket'
                    | 'Train'
                    | 'WashingMachine'
                    | 'Workshop'
                    | 'Wrench'
                  )
                | null;
              title: string;
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'checklist';
      }
    | {
        heading?: string | null;
        intro?: string | null;
        photos?:
          | {
              image: number | Media;
              /**
               * Shown with the photo, e.g. “Lounge area”. Leave empty to use the photo's alt text.
               */
              name?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional: a “View 3D Tour” button under the photos.
         */
        tour?: {
          label?: string | null;
          href?: string | null;
        };
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gallery';
      }
    | {
        heading: string;
        intro?: string | null;
        groups?:
          | {
              /**
               * Optional: a small label above the group.
               */
              label?: string | null;
              items?:
                | {
                    label: string;
                    icon:
                      | 'Api'
                      | 'Automate'
                      | 'BarKitchen'
                      | 'Basin'
                      | 'Bed'
                      | 'Bike'
                      | 'Bill'
                      | 'Bus'
                      | 'Calendar'
                      | 'CalendarCheck'
                      | 'Car'
                      | 'Cctv'
                      | 'Check'
                      | 'Chef'
                      | 'Cocktail'
                      | 'Community'
                      | 'Crowd'
                      | 'Database'
                      | 'DealFlow'
                      | 'Desk'
                      | 'Dining'
                      | 'DoorEntry'
                      | 'Dumbbell'
                      | 'FeasibilityModel'
                      | 'FruitBowl'
                      | 'Groceries'
                      | 'Guard'
                      | 'Hack'
                      | 'HandsHeart'
                      | 'Handshake'
                      | 'Help'
                      | 'Hob'
                      | 'Icon360'
                      | 'Info'
                      | 'IntegrateData'
                      | 'Integrations'
                      | 'Lion'
                      | 'LocationPin'
                      | 'Lock'
                      | 'Lounge'
                      | 'Mail'
                      | 'ManageMembership'
                      | 'MeetingTable'
                      | 'MemberSupport'
                      | 'Membership'
                      | 'Microwave'
                      | 'Outdoor'
                      | 'Oven'
                      | 'Padlock'
                      | 'People'
                      | 'Plane'
                      | 'Play'
                      | 'PrivateOffice'
                      | 'QuoteMark'
                      | 'Relationships'
                      | 'Reporting'
                      | 'Restaurant'
                      | 'RestaurantsNearby'
                      | 'RoomAllocation'
                      | 'RoomPricing'
                      | 'Roundel'
                      | 'Router'
                      | 'Scales'
                      | 'Shelves'
                      | 'SmartHome'
                      | 'SocialNetwork'
                      | 'Sofa'
                      | 'SprayBottle'
                      | 'Sprout'
                      | 'Star'
                      | 'SunCloud'
                      | 'TapeMeasure'
                      | 'TeamChat'
                      | 'TrackMarket'
                      | 'Train'
                      | 'WashingMachine'
                      | 'Workshop'
                      | 'Wrench';
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureGroups';
      }
    | {
        heading: string;
        intro?: string | null;
        /**
         * Cards for these locations (/admin → Locations), in this order. Each links to its own page.
         */
        locations: (number | Location)[];
        ctaLabel?: string | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'locationCards';
      }
    | {
        heading: string;
        intro?: string | null;
        /**
         * Cards for these rooms (/admin → Rooms), in this order. Each links to its own page.
         */
        rooms: (number | Room)[];
        ctaLabel?: string | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'roomCards';
      }
    | {
        heading?: string | null;
        intro?: string | null;
        cards?:
          | {
              title: string;
              text: string;
              image: number | Media;
              /**
               * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
               */
              position?: ('top' | 'bottom' | 'left' | 'right') | null;
              ctaLabel: string;
              ctaHref: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional, e.g. “Read more press articles”.
         */
        moreLink?: {
          label?: string | null;
          href?: string | null;
        };
        cardStyle?: ('dark' | 'light') | null;
        imageShape?: ('wide' | 'tall') | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'linkCards';
      }
    | {
        heading: string;
        /**
         * Leave a blank line between paragraphs.
         */
        body: string;
        images: {
          main: number | Media;
          top: number | Media;
          bottom: number | Media;
        };
        side?: ('left' | 'right') | null;
        /**
         * Optional: leave both empty for no button.
         */
        cta?: {
          label?: string | null;
          /**
           * A page, another site, mailto:… or #section
           */
          href?: string | null;
        };
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'collageSplit';
      }
    | {
        heading: string;
        intro?: string | null;
        people?:
          | {
              name: string;
              photo: number | Media;
              /**
               * Optional: their video, as a YouTube or Vimeo link or an .mp4.
               */
              video?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        heading: string;
        intro?: string | null;
        quotes?:
          | {
              quote: string;
              publication: string;
              /**
               * Optional: the publication's logo, ideally an SVG. Without one, its name is shown.
               */
              logo?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'pressQuotes';
      }
    | {
        heading: string;
        intro?: string | null;
        people?:
          | {
              name: string;
              role: string;
              photo: number | Media;
              /**
               * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
               */
              position?: ('top' | 'bottom' | 'left' | 'right') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamGrid';
      }
    | {
        heading: string;
        intro?: string | null;
        reviews?:
          | {
              name: string;
              /**
               * Stars, out of 5
               */
              rating: number;
              /**
               * Optional: their profile photo. Without one, their initials show.
               */
              photo?: (number | null) | Media;
              /**
               * Word for word. Leave a blank line between paragraphs.
               */
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'reviews';
      }
    | {
        heading: string;
        intro?: string | null;
        travelModes?:
          | {
              label: string;
              icon: 'underground' | 'overground' | 'bus' | 'car';
              /**
               * One step per line.
               */
              steps: string;
              mapsUrl: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Names the map for screen readers, e.g. “Old Oak”.
         */
        place: string;
        /**
         * Google Maps → Share → Embed a map → the src link.
         */
        mapEmbedUrl: string;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'directions';
      }
    | {
        heading: string;
        intro?: string | null;
        items?:
          | {
              question: string;
              /**
               * Leave a blank line between paragraphs.
               */
              answer: string;
              numbered?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional: a closing line under the questions.
         */
        outro?: string | null;
        /**
         * Optional: a button under the questions.
         */
        cta?: {
          label?: string | null;
          /**
           * A page, another site, mailto:… or #section
           */
          href?: string | null;
        };
        /**
         * Optional: link straight here with #anchor, e.g. “faq” for a “Read more” button linking to #faq.
         */
        anchor?: string | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        topics?:
          | {
              topic: string;
              items?:
                | {
                    question: string;
                    /**
                     * Leave a blank line between paragraphs.
                     */
                    answer: string;
                    numbered?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqDirectory';
      }
    | {
        /**
         * Lists the job pages (written in code, in content/careers.ts). Link here with #open-positions.
         */
        heading: string;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'openPositions';
      }
    | {
        /**
         * The logos and photos to download are in code (content/press.ts).
         */
        heading: string;
        intro?: string | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaKit';
      }
    | {
        heading: string;
        intro?: string | null;
        photos?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional: text ending in a link, e.g. “…following us on Instagram @thecollective_living”.
         */
        footer?: {
          text?: string | null;
          linkLabel?: string | null;
          linkHref?: string | null;
        };
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageCarousel';
      }
    | {
        heading: string;
        intro?: string | null;
        perks?:
          | {
              name: string;
              text: string;
              image: number | Media;
              /**
               * Optional: the partner's logo, shown on the photo.
               */
              logo?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'perkCards';
      }
    | {
        heading: string;
        intro: string;
        fileLabel: string;
        /**
         * Its address, e.g. /downloads/brochure.pdf
         */
        fileHref: string;
        image: number | Media;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'downloadCard';
      }
    | {
        cards?:
          | {
              heading: string;
              image: number | Media;
              /**
               * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
               */
              position?: ('top' | 'bottom' | 'left' | 'right') | null;
              ctaLabel: string;
              ctaHref: string;
              /**
               * Optional: an enquiry form instead of the link (which then isn't used).
               */
              enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
              id?: string | null;
            }[]
          | null;
        mobileShape?: ('short' | 'tall') | null;
        /**
         * Background colour. Alternate them down the page.
         */
        tone?: ('white' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'promoCards';
      }
    | {
        heading: string;
        intro?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'socialLinks';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for people who can't see it.
   */
  alt: string;
  blur?: string | null;
  source?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Working spaces, serviced living houses and event venues: their cards and their own pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * The page's address after its type's, e.g. /working/bedford-square for “bedford-square”.
   */
  slug: string;
  type: 'working' | 'serviced' | 'venue';
  /**
   * Neighbourhood, e.g. Bloomsbury
   */
  area: string;
  postcode: string;
  /**
   * e.g. “From £150 per month”, or a venue's capacity.
   */
  fromPrice: string;
  image: number | Media;
  /**
   * Transport and key facilities: the card's tiles and the page header's rows (up to 4).
   */
  features?:
    | {
        label: string;
        icon:
          | 'Api'
          | 'Automate'
          | 'BarKitchen'
          | 'Basin'
          | 'Bed'
          | 'Bike'
          | 'Bill'
          | 'Bus'
          | 'Calendar'
          | 'CalendarCheck'
          | 'Car'
          | 'Cctv'
          | 'Check'
          | 'Chef'
          | 'Cocktail'
          | 'Community'
          | 'Crowd'
          | 'Database'
          | 'DealFlow'
          | 'Desk'
          | 'Dining'
          | 'DoorEntry'
          | 'Dumbbell'
          | 'FeasibilityModel'
          | 'FruitBowl'
          | 'Groceries'
          | 'Guard'
          | 'Hack'
          | 'HandsHeart'
          | 'Handshake'
          | 'Help'
          | 'Hob'
          | 'Icon360'
          | 'Info'
          | 'IntegrateData'
          | 'Integrations'
          | 'Lion'
          | 'LocationPin'
          | 'Lock'
          | 'Lounge'
          | 'Mail'
          | 'ManageMembership'
          | 'MeetingTable'
          | 'MemberSupport'
          | 'Membership'
          | 'Microwave'
          | 'Outdoor'
          | 'Oven'
          | 'Padlock'
          | 'People'
          | 'Plane'
          | 'Play'
          | 'PrivateOffice'
          | 'QuoteMark'
          | 'Relationships'
          | 'Reporting'
          | 'Restaurant'
          | 'RestaurantsNearby'
          | 'RoomAllocation'
          | 'RoomPricing'
          | 'Roundel'
          | 'Router'
          | 'Scales'
          | 'Shelves'
          | 'SmartHome'
          | 'SocialNetwork'
          | 'Sofa'
          | 'SprayBottle'
          | 'Sprout'
          | 'Star'
          | 'SunCloud'
          | 'TapeMeasure'
          | 'TeamChat'
          | 'TrackMarket'
          | 'Train'
          | 'WashingMachine'
          | 'Workshop'
          | 'Wrench';
        id?: string | null;
      }[]
    | null;
  /**
   * Leave a blank line between paragraphs.
   */
  intro: string;
  gallery?:
    | {
        image: number | Media;
        /**
         * Shown with the photo, e.g. “Lounge area”. Leave empty to use the photo's alt text.
         */
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Pricing cards. Leave empty to leave pricing out (e.g. venues, priced on request).
   */
  prices?:
    | {
        label: string;
        amount: string;
        period: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Facilities, in groups (a label is optional). Working spaces can leave it empty to show the standard list every working space has.
   */
  included?:
    | {
        label?: string | null;
        items?:
          | {
              label: string;
              icon:
                | 'Api'
                | 'Automate'
                | 'BarKitchen'
                | 'Basin'
                | 'Bed'
                | 'Bike'
                | 'Bill'
                | 'Bus'
                | 'Calendar'
                | 'CalendarCheck'
                | 'Car'
                | 'Cctv'
                | 'Check'
                | 'Chef'
                | 'Cocktail'
                | 'Community'
                | 'Crowd'
                | 'Database'
                | 'DealFlow'
                | 'Desk'
                | 'Dining'
                | 'DoorEntry'
                | 'Dumbbell'
                | 'FeasibilityModel'
                | 'FruitBowl'
                | 'Groceries'
                | 'Guard'
                | 'Hack'
                | 'HandsHeart'
                | 'Handshake'
                | 'Help'
                | 'Hob'
                | 'Icon360'
                | 'Info'
                | 'IntegrateData'
                | 'Integrations'
                | 'Lion'
                | 'LocationPin'
                | 'Lock'
                | 'Lounge'
                | 'Mail'
                | 'ManageMembership'
                | 'MeetingTable'
                | 'MemberSupport'
                | 'Membership'
                | 'Microwave'
                | 'Outdoor'
                | 'Oven'
                | 'Padlock'
                | 'People'
                | 'Plane'
                | 'Play'
                | 'PrivateOffice'
                | 'QuoteMark'
                | 'Relationships'
                | 'Reporting'
                | 'Restaurant'
                | 'RestaurantsNearby'
                | 'RoomAllocation'
                | 'RoomPricing'
                | 'Roundel'
                | 'Router'
                | 'Scales'
                | 'Shelves'
                | 'SmartHome'
                | 'SocialNetwork'
                | 'Sofa'
                | 'SprayBottle'
                | 'Sprout'
                | 'Star'
                | 'SunCloud'
                | 'TapeMeasure'
                | 'TeamChat'
                | 'TrackMarket'
                | 'Train'
                | 'WashingMachine'
                | 'Workshop'
                | 'Wrench';
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Street address: drives the map and the “open in Maps” links. Without one, the map is left out.
   */
  address?: string | null;
  directionsIntro: string;
  travelModes?:
    | {
        label: string;
        icon: 'underground' | 'overground' | 'bus' | 'car';
        /**
         * One step per line.
         */
        steps: string;
        mapsUrl: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Old Oak's rooms: their cards, their own pages and their booking.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * The page's address: /locations/old-oak/rooms/ensuite for “ensuite”.
   */
  slug: string;
  /**
   * Weekly, e.g. “£245”. The card shows “£245 per week”.
   */
  price: string;
  /**
   * Shown under the room's name.
   */
  location: string;
  /**
   * The card's photo, the page's header and the gallery's first photo.
   */
  image: number | Media;
  /**
   * The card's tiles and the page's key facts (up to 4).
   */
  features?:
    | {
        label: string;
        icon:
          | 'Api'
          | 'Automate'
          | 'BarKitchen'
          | 'Basin'
          | 'Bed'
          | 'Bike'
          | 'Bill'
          | 'Bus'
          | 'Calendar'
          | 'CalendarCheck'
          | 'Car'
          | 'Cctv'
          | 'Check'
          | 'Chef'
          | 'Cocktail'
          | 'Community'
          | 'Crowd'
          | 'Database'
          | 'DealFlow'
          | 'Desk'
          | 'Dining'
          | 'DoorEntry'
          | 'Dumbbell'
          | 'FeasibilityModel'
          | 'FruitBowl'
          | 'Groceries'
          | 'Guard'
          | 'Hack'
          | 'HandsHeart'
          | 'Handshake'
          | 'Help'
          | 'Hob'
          | 'Icon360'
          | 'Info'
          | 'IntegrateData'
          | 'Integrations'
          | 'Lion'
          | 'LocationPin'
          | 'Lock'
          | 'Lounge'
          | 'Mail'
          | 'ManageMembership'
          | 'MeetingTable'
          | 'MemberSupport'
          | 'Membership'
          | 'Microwave'
          | 'Outdoor'
          | 'Oven'
          | 'Padlock'
          | 'People'
          | 'Plane'
          | 'Play'
          | 'PrivateOffice'
          | 'QuoteMark'
          | 'Relationships'
          | 'Reporting'
          | 'Restaurant'
          | 'RestaurantsNearby'
          | 'RoomAllocation'
          | 'RoomPricing'
          | 'Roundel'
          | 'Router'
          | 'Scales'
          | 'Shelves'
          | 'SmartHome'
          | 'SocialNetwork'
          | 'Sofa'
          | 'SprayBottle'
          | 'Sprout'
          | 'Star'
          | 'SunCloud'
          | 'TapeMeasure'
          | 'TeamChat'
          | 'TrackMarket'
          | 'Train'
          | 'WashingMachine'
          | 'Workshop'
          | 'Wrench';
        id?: string | null;
      }[]
    | null;
  /**
   * Leave a blank line between paragraphs.
   */
  about: string;
  /**
   * The gallery, after the room's photo.
   */
  photos?:
    | {
        image: number | Media;
        /**
         * Shown with the photo. Leave empty to use the photo's alt text.
         */
        name?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: the floor plan drawing. Left out until there is one.
   */
  floorPlan?: (number | null) | Media;
  /**
   * e.g. “Available now”
   */
  moveIn: string;
  /**
   * e.g. “17–19”
   */
  floor: string;
  /**
   * One per line, e.g. “12 months”. The first is picked to start with.
   */
  periods: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  floatingEnquiry?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              subtitle?: T;
              image?: T;
              imagePosition?: T;
              button?:
                | T
                | {
                    type?: T;
                    opens?: T;
                    href?: T;
                    enquiry?: T;
                    videoUrl?: T;
                    label?: T;
                    arrow?: T;
                  };
              id?: T;
              blockName?: T;
            };
        intro?:
          | T
          | {
              heading?: T;
              body?: T;
              layout?: T;
              buttons?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              enquiry?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        checklist?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              heading?: T;
              intro?: T;
              photos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    id?: T;
                  };
              tour?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        featureGroups?:
          | T
          | {
              heading?: T;
              intro?: T;
              groups?:
                | T
                | {
                    label?: T;
                    items?:
                      | T
                      | {
                          label?: T;
                          icon?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        locationCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              locations?: T;
              ctaLabel?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        roomCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              rooms?: T;
              ctaLabel?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        linkCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    image?: T;
                    position?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                  };
              moreLink?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              cardStyle?: T;
              imageShape?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        collageSplit?:
          | T
          | {
              heading?: T;
              body?: T;
              images?:
                | T
                | {
                    main?: T;
                    top?: T;
                    bottom?: T;
                  };
              side?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              intro?: T;
              people?:
                | T
                | {
                    name?: T;
                    photo?: T;
                    video?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        pressQuotes?:
          | T
          | {
              heading?: T;
              intro?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    publication?: T;
                    logo?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              heading?: T;
              intro?: T;
              people?:
                | T
                | {
                    name?: T;
                    role?: T;
                    photo?: T;
                    position?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              heading?: T;
              intro?: T;
              reviews?:
                | T
                | {
                    name?: T;
                    rating?: T;
                    photo?: T;
                    text?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        directions?:
          | T
          | {
              heading?: T;
              intro?: T;
              travelModes?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    steps?: T;
                    mapsUrl?: T;
                    id?: T;
                  };
              place?: T;
              mapEmbedUrl?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    numbered?: T;
                    id?: T;
                  };
              outro?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              anchor?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        faqDirectory?:
          | T
          | {
              topics?:
                | T
                | {
                    topic?: T;
                    items?:
                      | T
                      | {
                          question?: T;
                          answer?: T;
                          numbered?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        openPositions?:
          | T
          | {
              heading?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        mediaKit?:
          | T
          | {
              heading?: T;
              intro?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        imageCarousel?:
          | T
          | {
              heading?: T;
              intro?: T;
              photos?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              footer?:
                | T
                | {
                    text?: T;
                    linkLabel?: T;
                    linkHref?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        perkCards?:
          | T
          | {
              heading?: T;
              intro?: T;
              perks?:
                | T
                | {
                    name?: T;
                    text?: T;
                    image?: T;
                    logo?: T;
                    id?: T;
                  };
              tone?: T;
              id?: T;
              blockName?: T;
            };
        downloadCard?:
          | T
          | {
              heading?: T;
              intro?: T;
              fileLabel?: T;
              fileHref?: T;
              image?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        promoCards?:
          | T
          | {
              cards?:
                | T
                | {
                    heading?: T;
                    image?: T;
                    position?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    enquiry?: T;
                    id?: T;
                  };
              mobileShape?: T;
              tone?: T;
              id?: T;
              blockName?: T;
            };
        socialLinks?:
          | T
          | {
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  type?: T;
  area?: T;
  postcode?: T;
  fromPrice?: T;
  image?: T;
  features?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  intro?: T;
  gallery?:
    | T
    | {
        image?: T;
        name?: T;
        id?: T;
      };
  prices?:
    | T
    | {
        label?: T;
        amount?: T;
        period?: T;
        id?: T;
      };
  included?:
    | T
    | {
        label?: T;
        items?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
        id?: T;
      };
  address?: T;
  directionsIntro?: T;
  travelModes?:
    | T
    | {
        label?: T;
        icon?: T;
        steps?: T;
        mapsUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  price?: T;
  location?: T;
  image?: T;
  features?:
    | T
    | {
        label?: T;
        icon?: T;
        id?: T;
      };
  about?: T;
  photos?:
    | T
    | {
        image?: T;
        name?: T;
        id?: T;
      };
  floorPlan?: T;
  moveIn?: T;
  floor?: T;
  periods?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  blur?: T;
  source?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The site's three menus. Drag rows to reorder them, and untick Show to hide a link without deleting it. Changes show on every page as soon as you save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  menu?:
    | {
        /**
         * A small grey heading above its links. Leave empty for the first section (Home, Locations…), which has none.
         */
        heading?: string | null;
        items?:
          | {
              label: string;
              /**
               * Leave empty if it has sub-links: tapping it then opens them instead.
               */
              href?: string | null;
              /**
               * Untick to hide it without deleting it.
               */
              show?: boolean | null;
              /**
               * Optional: links that fold out under this one, e.g. Locations → Old Oak, Canary Wharf.
               */
              subLinks?:
                | {
                    label: string;
                    href: string;
                    /**
                     * Untick to hide it without deleting it.
                     */
                    show?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  desktop?:
    | {
        label: string;
        /**
         * “The menu's sections” shows the Menu tab's sections that have a heading, so they're kept in one place.
         */
        opens?: ('link' | 'dropdown' | 'menu') | null;
        href?: string | null;
        subLinks?:
          | {
              label: string;
              href: string;
              /**
               * Untick to hide it without deleting it.
               */
              show?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Untick to hide it without deleting it.
         */
        show?: boolean | null;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              /**
               * Untick to hide it without deleting it.
               */
              show?: boolean | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Untick to hide it without deleting it.
         */
        show?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Shown in the footer, on the Call us and Email us buttons, on the careers pages and in Social links. Changes show everywhere as soon as you save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactDetails".
 */
export interface ContactDetail {
  id: number;
  /**
   * As it's shown, e.g. “+44 (0) 207 183 5478”. Tapping it dials the number (without the “(0)”).
   */
  phone: string;
  email: string;
  /**
   * One line per line of the address. Shown on one line on desktop.
   */
  address: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The icons and button in every “Connect with us” section. Drag to reorder; untick Show to hide one. Changes show everywhere as soon as you save.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialLinks".
 */
export interface SocialLink {
  id: number;
  accounts?:
    | {
        /**
         * Its icon. Email goes to the address in Contact details.
         */
        platform: 'youtube' | 'twitter' | 'facebook' | 'instagram' | 'email';
        /**
         * The account's address, e.g. https://www.instagram.com/…
         */
        href?: string | null;
        /**
         * Read out by screen readers (the icon has no text), e.g. “The Collective on Instagram”.
         */
        label: string;
        /**
         * Untick to hide it without deleting it.
         */
        show?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: the button under the icons, e.g. a newsletter sign-up. Leave the link empty for no button.
   */
  newsletter?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * What every page of a type shares: each working space's, house's, venue's or room's own content is in Locations and Rooms; the parts they all have in common are here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locationPages".
 */
export interface LocationPage {
  id: number;
  working: {
    includedIntro: string;
    /**
     * Shown on a working space's page unless it has its own list (Locations → its Page tab).
     */
    included?:
      | {
          /**
           * Optional: a small label above the group.
           */
          label?: string | null;
          items?:
            | {
                label: string;
                icon:
                  | 'Api'
                  | 'Automate'
                  | 'BarKitchen'
                  | 'Basin'
                  | 'Bed'
                  | 'Bike'
                  | 'Bill'
                  | 'Bus'
                  | 'Calendar'
                  | 'CalendarCheck'
                  | 'Car'
                  | 'Cctv'
                  | 'Check'
                  | 'Chef'
                  | 'Cocktail'
                  | 'Community'
                  | 'Crowd'
                  | 'Database'
                  | 'DealFlow'
                  | 'Desk'
                  | 'Dining'
                  | 'DoorEntry'
                  | 'Dumbbell'
                  | 'FeasibilityModel'
                  | 'FruitBowl'
                  | 'Groceries'
                  | 'Guard'
                  | 'Hack'
                  | 'HandsHeart'
                  | 'Handshake'
                  | 'Help'
                  | 'Hob'
                  | 'Icon360'
                  | 'Info'
                  | 'IntegrateData'
                  | 'Integrations'
                  | 'Lion'
                  | 'LocationPin'
                  | 'Lock'
                  | 'Lounge'
                  | 'Mail'
                  | 'ManageMembership'
                  | 'MeetingTable'
                  | 'MemberSupport'
                  | 'Membership'
                  | 'Microwave'
                  | 'Outdoor'
                  | 'Oven'
                  | 'Padlock'
                  | 'People'
                  | 'Plane'
                  | 'Play'
                  | 'PrivateOffice'
                  | 'QuoteMark'
                  | 'Relationships'
                  | 'Reporting'
                  | 'Restaurant'
                  | 'RestaurantsNearby'
                  | 'RoomAllocation'
                  | 'RoomPricing'
                  | 'Roundel'
                  | 'Router'
                  | 'Scales'
                  | 'Shelves'
                  | 'SmartHome'
                  | 'SocialNetwork'
                  | 'Sofa'
                  | 'SprayBottle'
                  | 'Sprout'
                  | 'Star'
                  | 'SunCloud'
                  | 'TapeMeasure'
                  | 'TeamChat'
                  | 'TrackMarket'
                  | 'Train'
                  | 'WashingMachine'
                  | 'Workshop'
                  | 'Wrench';
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    pricingIntro: string;
    /**
     * Under the gallery. Leave the link empty for no button.
     */
    tour?: {
      label?: string | null;
      href?: string | null;
    };
    /**
     * The cards at the bottom of every page of this type.
     */
    promos?:
      | {
          heading: string;
          image: number | Media;
          /**
           * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
           */
          position?: ('top' | 'bottom' | 'left' | 'right') | null;
          ctaLabel: string;
          ctaHref: string;
          /**
           * Optional: an enquiry form instead of the link (which then isn't used).
           */
          enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
          id?: string | null;
        }[]
      | null;
  };
  serviced: {
    includedIntro: string;
    pricingIntro: string;
    /**
     * The cards at the bottom of every page of this type.
     */
    promos?:
      | {
          heading: string;
          image: number | Media;
          /**
           * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
           */
          position?: ('top' | 'bottom' | 'left' | 'right') | null;
          ctaLabel: string;
          ctaHref: string;
          /**
           * Optional: an enquiry form instead of the link (which then isn't used).
           */
          enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
          id?: string | null;
        }[]
      | null;
  };
  venues: {
    includedHeading: string;
    includedIntro: string;
    /**
     * The cards at the bottom of every page of this type.
     */
    promos?:
      | {
          heading: string;
          image: number | Media;
          /**
           * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
           */
          position?: ('top' | 'bottom' | 'left' | 'right') | null;
          ctaLabel: string;
          ctaHref: string;
          /**
           * Optional: an enquiry form instead of the link (which then isn't used).
           */
          enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
          id?: string | null;
        }[]
      | null;
  };
  rooms: {
    included?:
      | {
          label: string;
          icon:
            | 'Api'
            | 'Automate'
            | 'BarKitchen'
            | 'Basin'
            | 'Bed'
            | 'Bike'
            | 'Bill'
            | 'Bus'
            | 'Calendar'
            | 'CalendarCheck'
            | 'Car'
            | 'Cctv'
            | 'Check'
            | 'Chef'
            | 'Cocktail'
            | 'Community'
            | 'Crowd'
            | 'Database'
            | 'DealFlow'
            | 'Desk'
            | 'Dining'
            | 'DoorEntry'
            | 'Dumbbell'
            | 'FeasibilityModel'
            | 'FruitBowl'
            | 'Groceries'
            | 'Guard'
            | 'Hack'
            | 'HandsHeart'
            | 'Handshake'
            | 'Help'
            | 'Hob'
            | 'Icon360'
            | 'Info'
            | 'IntegrateData'
            | 'Integrations'
            | 'Lion'
            | 'LocationPin'
            | 'Lock'
            | 'Lounge'
            | 'Mail'
            | 'ManageMembership'
            | 'MeetingTable'
            | 'MemberSupport'
            | 'Membership'
            | 'Microwave'
            | 'Outdoor'
            | 'Oven'
            | 'Padlock'
            | 'People'
            | 'Plane'
            | 'Play'
            | 'PrivateOffice'
            | 'QuoteMark'
            | 'Relationships'
            | 'Reporting'
            | 'Restaurant'
            | 'RestaurantsNearby'
            | 'RoomAllocation'
            | 'RoomPricing'
            | 'Roundel'
            | 'Router'
            | 'Scales'
            | 'Shelves'
            | 'SmartHome'
            | 'SocialNetwork'
            | 'Sofa'
            | 'SprayBottle'
            | 'Sprout'
            | 'Star'
            | 'SunCloud'
            | 'TapeMeasure'
            | 'TeamChat'
            | 'TrackMarket'
            | 'Train'
            | 'WashingMachine'
            | 'Workshop'
            | 'Wrench';
          id?: string | null;
        }[]
      | null;
    about: {
      heading: string;
      /**
       * Leave a blank line between paragraphs.
       */
      text: string;
      poster: number | Media;
      /**
       * YouTube, Vimeo or an .mp4, played over the poster.
       */
      video: string;
    };
    /**
     * Leave a blank line between paragraphs.
     */
    coLivingAbout: string;
    /**
     * The cards at the bottom of every page of this type.
     */
    promos?:
      | {
          heading: string;
          image: number | Media;
          /**
           * Which edge of the photo stays in view when it's cropped. Clear it (×) to centre it again.
           */
          position?: ('top' | 'bottom' | 'left' | 'right') | null;
          ctaLabel: string;
          ctaHref: string;
          /**
           * Optional: an enquiry form instead of the link (which then isn't used).
           */
          enquiry?: ('living' | 'working' | 'serviced' | 'events' | 'waitlist') | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  menu?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              show?: T;
              subLinks?:
                | T
                | {
                    label?: T;
                    href?: T;
                    show?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  desktop?:
    | T
    | {
        label?: T;
        opens?: T;
        href?: T;
        subLinks?:
          | T
          | {
              label?: T;
              href?: T;
              show?: T;
              id?: T;
            };
        show?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              show?: T;
              id?: T;
            };
        show?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactDetails_select".
 */
export interface ContactDetailsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "socialLinks_select".
 */
export interface SocialLinksSelect<T extends boolean = true> {
  accounts?:
    | T
    | {
        platform?: T;
        href?: T;
        label?: T;
        show?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locationPages_select".
 */
export interface LocationPagesSelect<T extends boolean = true> {
  working?:
    | T
    | {
        includedIntro?: T;
        included?:
          | T
          | {
              label?: T;
              items?:
                | T
                | {
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
            };
        pricingIntro?: T;
        tour?:
          | T
          | {
              label?: T;
              href?: T;
            };
        promos?:
          | T
          | {
              heading?: T;
              image?: T;
              position?: T;
              ctaLabel?: T;
              ctaHref?: T;
              enquiry?: T;
              id?: T;
            };
      };
  serviced?:
    | T
    | {
        includedIntro?: T;
        pricingIntro?: T;
        promos?:
          | T
          | {
              heading?: T;
              image?: T;
              position?: T;
              ctaLabel?: T;
              ctaHref?: T;
              enquiry?: T;
              id?: T;
            };
      };
  venues?:
    | T
    | {
        includedHeading?: T;
        includedIntro?: T;
        promos?:
          | T
          | {
              heading?: T;
              image?: T;
              position?: T;
              ctaLabel?: T;
              ctaHref?: T;
              enquiry?: T;
              id?: T;
            };
      };
  rooms?:
    | T
    | {
        included?:
          | T
          | {
              label?: T;
              icon?: T;
              id?: T;
            };
        about?:
          | T
          | {
              heading?: T;
              text?: T;
              poster?: T;
              video?: T;
            };
        coLivingAbout?: T;
        promos?:
          | T
          | {
              heading?: T;
              image?: T;
              position?: T;
              ctaLabel?: T;
              ctaHref?: T;
              enquiry?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}